version: "3.3"
services:
  image:
    build: .
    command: "steamcmd-wrapper ./badlads/BadLadsServer.sh -SteamServerName $(<SERVERNAME)"
    environment:
      STEAMCMD_APP_ID: "1203110"
      STEAMCMD_SKIP: "false"
      USER_UID: "1000"
      USER_GID: "1000"
    network_mode: "host"
    volumes:
      - "./data:/data"
