version: "3.3"
services:
  badlads:
    build: .
    environment:
      STEAMCMD_APP_ID: "1203110"
      STEAMCMD_SKIP: "false"
      USER_UID: "1000"
      USER_GID: "1000"
      SERVERNAME: "BadLadsComposedName"
      BADLADS_ARGS: "-useperfthreads"
    network_mode: "host"
    volumes:
      - "./data:/data"
