app_data:
  image: zobees/steamcmd:0.0.1
  command: echo "Example data volume"
  volumes:
    - /home/steam/steamcmd
    - /home/steam/app

app:
  image: zobees/steamcmd:0.0.1
  env_file:
    - ./app.env
    - ./auth.env
  ports:
    - "26900-26902"
    - "26900-26902/udp"
  volumes_from:
    - app_data
