version: "3.3"
services:
  steamcmd:
    build: .
    image: zobees/steamcmd
    command: "./7DaysToDieServer.x86_64 -logfile /dev/stdout -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated"
    environment:
      STEAMCMD_APP_ID: "294420"
      STEAMCMD_BETA: "latest_experimental"
    ports:
      - "26900-26902:26900-26902"
      - "26900-26902:26900-26902/udp"
    volumes:
      - "./data:/data"
